### ISSUE TITLE
一直下载不下来

### ISSUE THREAD

**Issue by zhaohui007** [ng-alain/archive-docs#1]
fatal: unable to access 'https://github.com/ng-alain/archive-docs.git/': OpenSSL SSL_read: Connection was reset, errno 10054
一直下载不下来 开了魔法上网了

**Comment by cipchk** [comment]
```bash
git clone --depth 1 https://github.com/ng-alain/archive-docs.git ng-alain-doc
```

如果不行， 可以尝试使用 [Docker 版本](https://hub.docker.com/r/cipchk/ng-alain-docs)。

或国内镜像。

```bash
https://gitee.com/ng-alain/archive-docs
```
